<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="flowchart" nsURI="flwochart" nsPrefix="flowchart">
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" ordered="false"
        upperBound="-1" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//Feature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Page">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" ordered="false"
        upperBound="-1" eType="#//Content" containment="true" eOpposite="#//Content/page">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Content" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="page" eType="#//Page" eOpposite="#//Page/contents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="D_Content" abstract="true" eSuperTypes="#//Content">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" ordered="false"
        upperBound="-1" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Static_Content" eSuperTypes="#//Content"/>
  <eClassifiers xsi:type="ecore:EClass" name="Index" eSuperTypes="#//D_Content"/>
  <eClassifiers xsi:type="ecore:EClass" name="Individual" eSuperTypes="#//D_Content"/>
</ecore:EPackage>
